### ISSUE TITLE
Label cannot be found in the document

### ISSUE THREAD

**Issue by komape** [ENIB-Community/glossarium#41] opened 2024-05-28 10:38 UTC
I'm receiving the following error:

```
error: label `<entsoe>` does not exist in the document
   ┌─ @preview/glossarium:0.4.0/glossarium.typ:53:8
   │
53 │       [#link(label(entry.key), textLink)#label(__glossary_label_prefix + entry.key)]
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is my document:

```typst
#import "@preview/glossarium:0.4.0": make-glossary, print-glossary, gls, glspl 

#show: make-glossary

// some paragraphs

The main data source is the transparency platform from #gls("entsoe"). // ...

// more text

#print-glossary(
  (
    (
      key: "entsoe", 
      short: "ENTSO-E", 
      long: "European Network of Transmission System Operators for Electricity", 
      desc: [ENTSO-E is an association representing 42 electricity transmission system operators (TSOs) from 35 countries across Europe, working to ensure a reliable, efficient, and sustainable electricity supply.],
      group: "Accronyms",
    ),
  )
)
```

I receive the error both in the web app as well as when I compile it locally. Using `@entsoe` instead of `#gls("entsoe")` results in the following error:

```
error: label `<entsoe>` does not exist in the document
   ┌─ main.typ:48:55
   │
48 │ The main data source is the transparency platform from @entsoe.
   │      
```

What am I doing wrong? Do I miss something?

**Comment by slashformotion** [comment] 2024-05-28 14:41
this is caused by a bug fixed in v0.4.1, which is not released yet on the preview namespace. You can track the status of the associated merge request here: https://github.com/typst/packages/pull/702. 

In the meantime, you can download the glossarium sources at v0.4.1 or use a version before v0.4.0 if you have an urgent need to get this working.

Tell me if I can do something else to help you.

**Comment by komape** [comment] 2024-05-29 06:41
@slashformotion Thanks for the quick response. I'll just wait for v0.4.1 👍

> In the meantime, you can [...] use a version before v0.4.0 if you have an urgent need to get this working.

@slashformotion The error also occurred with versions before v0.4.0.

**Comment by slashformotion** [comment] 2024-05-30 08:17
> @slashformotion Thanks for the quick response. I'll just wait for v0.4.1 👍

v.0.4.1 is now released. 

> @slashformotion The error also occurred with versions before v0.4.0.

You are right, the bug was introduced in v0.3.0, sorry.

**Closed by slashformotion** 2024-05-30 08:17 UTC
